services:
  app:
    image: ${DOCKER_USERNAME}/couple-map-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
