springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
  oauth:
    redirect-base-url: ${OAUTH_REDIRECT_BASE_URL}
